API Key          JOBjnO6qKRqAJWGlE9nUM7rpm
API Key Secret   ILVobAXWPX7GgcyBziurFmlaQL7bDXMW5zaDEscCdmFqLYykVh

###

GET https://api.twitter.com/2/tweets/20
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAANRraQEAAAAAZ%2FPlHNOtO1fuRH2WidAKT9uoivQ%3DI1EkWG4yDk8ozJFoiBlsJ4AcRwsIkmX9HxdY6gquEsCeIr4lNO
